import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="k_i6d61">
            <body className="w-[1441px]" data-oid="krpqj04">
                {children}
            </body>
        </html>
    );
}
